---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: springci/spring-hateoas-examples-8-jdk-with-graphviz

inputs:
- name: spring-hateoas-examples-github

outputs:
- name: spring-hateoas-examples-artifactory

caches:
- path: maven

run:
  path: spring-hateoas-examples-github/ci/build.sh
