---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: 8-jdk

inputs:
- name: spring-hateoas-examples-github

outputs:
- name: spring-hateoas-examples-artifactory

caches:
- path: maven

run:
  path: spring-hateoas-examples-github/ci/build.sh
